<a href="https://colab.research.google.com/github/chiragkulkarni3/bayesFinal/blob/main/BayesFinal.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [34]:
import pandas as pd 
import datetime
import numpy as np

In [19]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
#Chirag
fundamentals = pd.read_csv("drive/MyDrive/Colab Notebooks/fundamentals.csv")
fundamentals

      Unnamed: 0  ... Estimated Shares Outstanding
0              0  ...                 3.350000e+08
1              1  ...                 1.630222e+08
2              2  ...                 7.169154e+08
3              3  ...                 6.681299e+08
4              4  ...                 7.328355e+07
...          ...  ...                          ...
1776        1776  ...                 2.578925e+08
1777        1777  ...                 4.990099e+08
1778        1778  ...                 5.025862e+08
1779        1779  ...                 4.985294e+08
1780        1780  ...                          NaN

[1781 rows x 79 columns]

In [ ]:
fundamentals["Period Ending"] = pd.to_datetime(fundamentals["Period Ending"])
days = datetime.timedelta(1)
year = datetime.timedelta(364)
fundamentals["PeriodAdjusted"] = fundamentals["Period Ending"] - days
fundamentals["PeriodLagged"] = fundamentals["Period Ending"] + year
fundamentals

NameError: ignored

In [ ]:

prices = pd.read_csv("drive/MyDrive/Colab Notebooks/prices-split-adjusted.csv")
prices

              date symbol        open  ...         low        high     volume
0       2016-01-05   WLTW  123.430000  ...  122.309998  126.250000  2163600.0
1       2016-01-06   WLTW  125.239998  ...  119.940002  125.540001  2386400.0
2       2016-01-07   WLTW  116.379997  ...  114.930000  119.739998  2489500.0
3       2016-01-08   WLTW  115.480003  ...  113.500000  117.440002  2006300.0
4       2016-01-11   WLTW  117.010002  ...  114.089996  117.330002  1408600.0
...            ...    ...         ...  ...         ...         ...        ...
851259  2016-12-30    ZBH  103.309998  ...  102.849998  103.930000   973800.0
851260  2016-12-30   ZION   43.070000  ...   42.689999   43.310001  1938100.0
851261  2016-12-30    ZTS   53.639999  ...   53.270000   53.740002  1701200.0
851262  2016-12-30    AIV   44.730000  ...   44.410000   45.590000  1380900.0
851263  2016-12-30    FTV   54.200001  ...   53.389999   54.480000   705100.0

[851264 rows x 7 columns]

In [ ]:
prices["date"] = pd.to_datetime(prices["date"])
prices

             date symbol        open  ...         low        high     volume
0      2016-01-05   WLTW  123.430000  ...  122.309998  126.250000  2163600.0
1      2016-01-06   WLTW  125.239998  ...  119.940002  125.540001  2386400.0
2      2016-01-07   WLTW  116.379997  ...  114.930000  119.739998  2489500.0
3      2016-01-08   WLTW  115.480003  ...  113.500000  117.440002  2006300.0
4      2016-01-11   WLTW  117.010002  ...  114.089996  117.330002  1408600.0
...           ...    ...         ...  ...         ...         ...        ...
851259 2016-12-30    ZBH  103.309998  ...  102.849998  103.930000   973800.0
851260 2016-12-30   ZION   43.070000  ...   42.689999   43.310001  1938100.0
851261 2016-12-30    ZTS   53.639999  ...   53.270000   53.740002  1701200.0
851262 2016-12-30    AIV   44.730000  ...   44.410000   45.590000  1380900.0
851263 2016-12-30    FTV   54.200001  ...   53.389999   54.480000   705100.0

[851264 rows x 7 columns]

In [ ]:
joined = pd.merge(fundamentals, prices, left_on=["Ticker Symbol", "PeriodAdjusted"], right_on=["symbol","date"], how="inner")
#vars = ["PeriodAdjusted", "date","symbol", "open","low","high","volume"]
joined

      Unnamed: 0 Ticker Symbol Period Ending  ...         low        high     volume
0              1           AAL    2013-12-31  ...   24.650000   25.250000  8840800.0
1              2           AAL    2014-12-31  ...   52.830002   53.700001  8063100.0
2              3           AAL    2015-12-31  ...   42.459999   43.639999  5463600.0
3              4           AAP    2012-12-29  ...   70.790001   71.849998   422100.0
4              5           AAP    2013-12-28  ...  109.629997  111.940002   364200.0
...          ...           ...           ...  ...         ...         ...        ...
1360        1776          ZION    2015-12-31  ...   27.420000   27.770000  1010700.0
1361        1777           ZTS    2013-12-31  ...   32.540001   32.840000  1803600.0
1362        1778           ZTS    2014-12-31  ...   43.090000   44.099998  2251100.0
1363        1779           ZTS    2015-12-31  ...   48.009998   48.650002  1453700.0
1364        1780           ZTS    2016-12-31  ...   53.270000   53.740002  1701200.0

[1365 rows x 88 columns]

In [ ]:
joined_lag = pd.merge(joined, prices, left_on=["Ticker Symbol", "PeriodLagged"], right_on=["symbol","date"], how="inner")
joined_lag

      Unnamed: 0 Ticker Symbol Period Ending  ...      low_y     high_y   volume_y
0              1           AAL    2013-12-31  ...  52.830002  53.700001  8063100.0
1              2           AAL    2014-12-31  ...  42.459999  43.639999  5463600.0
2              3           AAL    2015-12-31  ...  46.959999  48.000000  3709300.0
3             13          ABBV    2013-12-31  ...  66.019997  67.160004  5568800.0
4             14          ABBV    2014-12-31  ...  59.310001  60.119999  5220300.0
...          ...           ...           ...  ...        ...        ...        ...
1051        1775          ZION    2014-12-31  ...  27.420000  27.770000  1010700.0
1052        1776          ZION    2015-12-31  ...  42.630001  43.639999  1551600.0
1053        1777           ZTS    2013-12-31  ...  43.090000  44.099998  2251100.0
1054        1778           ZTS    2014-12-31  ...  48.009998  48.650002  1453700.0
1055        1779           ZTS    2015-12-31  ...  53.400002  53.779999  1046700.0

[1056 rows x 95 columns]

In [ ]:
joined_lag["priceChange"] = joined_lag["close_y"]/joined_lag["close_x"]
joined_lag["priceChange"].describe()

count    1056.000000
mean        1.090414
std         0.259384
min         0.224033
25%         0.943898
50%         1.082684
75%         1.225684
max         2.504597
Name: priceChange, dtype: float64

In [ ]:
spPerformance = {"Year":[2012, 2013, 2014,2015,2016], "Market Performance": [1.2960, 1.1139, 0.9927, 1.0954, 1.1942]}
marketPerf = pd.DataFrame(data=spPerformance)
marketPerf

   Year  Market Performance
0  2012              1.2960
1  2013              1.1139
2  2014              0.9927
3  2015              1.0954
4  2016              1.1942

In [ ]:
total_data = pd.merge(joined_lag, marketPerf, left_on=["For Year"], right_on=["Year"])
total_data["perc_performance"] = total_data["priceChange"]-total_data["Market Performance"]

In [ ]:
total_data["perc_performance"].describe()

count    1024.000000
mean        0.023860
std         0.247930
min        -0.768667
25%        -0.117178
50%         0.014894
75%         0.152590
max         1.409197
Name: perc_performance, dtype: float64

# Response Variable Encoding: 
**Good (Outperformance):** [.06, inf)

**Neutral (Neither outperformed nor underperformed significantly):** [-0.06, 0.06)

**Bad (Underperformance):** [-inf, -0.06)

In [20]:
total_data["performance"] = pd.cut(total_data["perc_performance"], bins=[-1000,-0.059,0.06,1000], labels=("Underperformed", "Neutral", "Outperformed"))
total_data["performance"].value_counts()

Outperformed      418
Underperformed    365
Neutral           241
Name: performance, dtype: int64

In [21]:
list(total_data.columns)

['Unnamed: 0',
 'Ticker Symbol',
 'Period Ending',
 'Accounts Payable',
 'Accounts Receivable',
 "Add'l income/expense items",
 'After Tax ROE',
 'Capital Expenditures',
 'Capital Surplus',
 'Cash Ratio',
 'Cash and Cash Equivalents',
 'Changes in Inventories',
 'Common Stocks',
 'Cost of Revenue',
 'Current Ratio',
 'Deferred Asset Charges',
 'Deferred Liability Charges',
 'Depreciation',
 'Earnings Before Interest and Tax',
 'Earnings Before Tax',
 'Effect of Exchange Rate',
 'Equity Earnings/Loss Unconsolidated Subsidiary',
 'Fixed Assets',
 'Goodwill',
 'Gross Margin',
 'Gross Profit',
 'Income Tax',
 'Intangible Assets',
 'Interest Expense',
 'Inventory',
 'Investments',
 'Liabilities',
 'Long-Term Debt',
 'Long-Term Investments',
 'Minority Interest',
 'Misc. Stocks',
 'Net Borrowings',
 'Net Cash Flow',
 'Net Cash Flow-Operating',
 'Net Cash Flows-Financing',
 'Net Cash Flows-Investing',
 'Net Income',
 'Net Income Adjustments',
 'Net Income Applicable to Common Shareholders',
 'Net Income-Cont. Operations',
 'Net Receivables',
 'Non-Recurring Items',
 'Operating Income',
 'Operating Margin',
 'Other Assets',
 'Other Current Assets',
 'Other Current Liabilities',
 'Other Equity',
 'Other Financing Activities',
 'Other Investing Activities',
 'Other Liabilities',
 'Other Operating Activities',
 'Other Operating Items',
 'Pre-Tax Margin',
 'Pre-Tax ROE',
 'Profit Margin',
 'Quick Ratio',
 'Research and Development',
 'Retained Earnings',
 'Sale and Purchase of Stock',
 'Sales, General and Admin.',
 'Short-Term Debt / Current Portion of Long-Term Debt',
 'Short-Term Investments',
 'Total Assets',
 'Total Current Assets',
 'Total Current Liabilities',
 'Total Equity',
 'Total Liabilities',
 'Total Liabilities & Equity',
 'Total Revenue',
 'Treasury Stock',
 'For Year',
 'Earnings Per Share',
 'Estimated Shares Outstanding',
 'PeriodAdjusted',
 'PeriodLagged',
 'date_x',
 'symbol_x',
 'open_x',
 'close_x',
 'low_x',
 'high_x',
 'volume_x',
 'date_y',
 'symbol_y',
 'open_y',
 'close_y',
 'low_y',
 'high_y',
 'volume_y',
 'priceChange',
 'Year',
 'Market Performance',
 'perc_performance',
 'performance']

In [22]:
vars = ["Unnamed: 0", "For Year", "Period Ending", "Period Adjusted", "PeriodLagged", "date_x", "symbol_x", "open_x", ]

After Tax ROE
Cash Ratio
Current Ratio
Gross Margin
Operating Margin
Pre-Tax Margin
Pre-Tax ROE
Profit Margin
Quick Ratio

In [25]:
total_data["Receivables Turnover"] = total_data["Total Revenue"]/total_data["Accounts Receivable"]
total_data["Inventory Turnover"] = total_data["Cost of Revenue"]/total_data["Inventory"]
total_data["Debt Ratio"] = total_data["Total Liabilities"]/total_data["Total Assets"]
total_data["Return on Assets"] = total_data["Net Income"]/total_data["Total Assets"]

In [28]:
vars = ["After Tax ROE", "Cash Ratio", "Current Ratio", "Gross Margin", "Operating Margin", "Pre-Tax Margin", "Pre-Tax ROE", "Profit Margin", "Quick Ratio", "Receivables Turnover", "Inventory Turnover", "Debt Ratio", "Return on Assets", "performance"]

In [37]:
final_data = total_data[vars]
final_data_v1 = final_data[~final_data.isin([np.nan, np.inf, -np.inf]).any(1)] #dropped nas and infinity values

In [40]:
final_data_v1.to_csv("cleaned_data.csv")