<a href="https://colab.research.google.com/github/chiragkulkarni3/bayesFinal/blob/main/BayesFinal.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd 
import datetime
import numpy as np
from sklearn.model_selection import train_test_split

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

#Data Set-up

In [ ]:
#Chirag
fundamentals = pd.read_csv("drive/MyDrive/Colab Notebooks/fundamentals.csv")
fundamentals

      Unnamed: 0  ... Estimated Shares Outstanding
0              0  ...                 3.350000e+08
1              1  ...                 1.630222e+08
2              2  ...                 7.169154e+08
3              3  ...                 6.681299e+08
4              4  ...                 7.328355e+07
...          ...  ...                          ...
1776        1776  ...                 2.578925e+08
1777        1777  ...                 4.990099e+08
1778        1778  ...                 5.025862e+08
1779        1779  ...                 4.985294e+08
1780        1780  ...                          NaN

[1781 rows x 79 columns]

In [ ]:
fundamentals["Period Ending"] = pd.to_datetime(fundamentals["Period Ending"])
days = datetime.timedelta(1)
year = datetime.timedelta(364)
fundamentals["PeriodAdjusted"] = fundamentals["Period Ending"] - days
fundamentals["PeriodLagged"] = fundamentals["Period Ending"] + year
fundamentals

      Unnamed: 0 Ticker Symbol  ... PeriodAdjusted  PeriodLagged
0              0           AAL  ...     2012-12-30    2013-12-30
1              1           AAL  ...     2013-12-30    2014-12-30
2              2           AAL  ...     2014-12-30    2015-12-30
3              3           AAL  ...     2015-12-30    2016-12-29
4              4           AAP  ...     2012-12-28    2013-12-28
...          ...           ...  ...            ...           ...
1776        1776          ZION  ...     2015-12-30    2016-12-29
1777        1777           ZTS  ...     2013-12-30    2014-12-30
1778        1778           ZTS  ...     2014-12-30    2015-12-30
1779        1779           ZTS  ...     2015-12-30    2016-12-29
1780        1780           ZTS  ...     2016-12-30    2017-12-30

[1781 rows x 81 columns]

In [ ]:

prices = pd.read_csv("drive/MyDrive/Colab Notebooks/prices-split-adjusted.csv")
prices

              date symbol        open  ...         low        high     volume
0       2016-01-05   WLTW  123.430000  ...  122.309998  126.250000  2163600.0
1       2016-01-06   WLTW  125.239998  ...  119.940002  125.540001  2386400.0
2       2016-01-07   WLTW  116.379997  ...  114.930000  119.739998  2489500.0
3       2016-01-08   WLTW  115.480003  ...  113.500000  117.440002  2006300.0
4       2016-01-11   WLTW  117.010002  ...  114.089996  117.330002  1408600.0
...            ...    ...         ...  ...         ...         ...        ...
851259  2016-12-30    ZBH  103.309998  ...  102.849998  103.930000   973800.0
851260  2016-12-30   ZION   43.070000  ...   42.689999   43.310001  1938100.0
851261  2016-12-30    ZTS   53.639999  ...   53.270000   53.740002  1701200.0
851262  2016-12-30    AIV   44.730000  ...   44.410000   45.590000  1380900.0
851263  2016-12-30    FTV   54.200001  ...   53.389999   54.480000   705100.0

[851264 rows x 7 columns]

In [ ]:
prices["date"] = pd.to_datetime(prices["date"])
prices

             date symbol        open  ...         low        high     volume
0      2016-01-05   WLTW  123.430000  ...  122.309998  126.250000  2163600.0
1      2016-01-06   WLTW  125.239998  ...  119.940002  125.540001  2386400.0
2      2016-01-07   WLTW  116.379997  ...  114.930000  119.739998  2489500.0
3      2016-01-08   WLTW  115.480003  ...  113.500000  117.440002  2006300.0
4      2016-01-11   WLTW  117.010002  ...  114.089996  117.330002  1408600.0
...           ...    ...         ...  ...         ...         ...        ...
851259 2016-12-30    ZBH  103.309998  ...  102.849998  103.930000   973800.0
851260 2016-12-30   ZION   43.070000  ...   42.689999   43.310001  1938100.0
851261 2016-12-30    ZTS   53.639999  ...   53.270000   53.740002  1701200.0
851262 2016-12-30    AIV   44.730000  ...   44.410000   45.590000  1380900.0
851263 2016-12-30    FTV   54.200001  ...   53.389999   54.480000   705100.0

[851264 rows x 7 columns]

In [ ]:
joined = pd.merge(fundamentals, prices, left_on=["Ticker Symbol", "PeriodAdjusted"], right_on=["symbol","date"], how="inner")
#vars = ["PeriodAdjusted", "date","symbol", "open","low","high","volume"]
joined

      Unnamed: 0 Ticker Symbol Period Ending  ...         low        high     volume
0              1           AAL    2013-12-31  ...   24.650000   25.250000  8840800.0
1              2           AAL    2014-12-31  ...   52.830002   53.700001  8063100.0
2              3           AAL    2015-12-31  ...   42.459999   43.639999  5463600.0
3              4           AAP    2012-12-29  ...   70.790001   71.849998   422100.0
4              5           AAP    2013-12-28  ...  109.629997  111.940002   364200.0
...          ...           ...           ...  ...         ...         ...        ...
1360        1776          ZION    2015-12-31  ...   27.420000   27.770000  1010700.0
1361        1777           ZTS    2013-12-31  ...   32.540001   32.840000  1803600.0
1362        1778           ZTS    2014-12-31  ...   43.090000   44.099998  2251100.0
1363        1779           ZTS    2015-12-31  ...   48.009998   48.650002  1453700.0
1364        1780           ZTS    2016-12-31  ...   53.270000   53.740002  1701200.0

[1365 rows x 88 columns]

In [ ]:
joined_lag = pd.merge(joined, prices, left_on=["Ticker Symbol", "PeriodLagged"], right_on=["symbol","date"], how="inner")
joined_lag

      Unnamed: 0 Ticker Symbol Period Ending  ...      low_y     high_y   volume_y
0              1           AAL    2013-12-31  ...  52.830002  53.700001  8063100.0
1              2           AAL    2014-12-31  ...  42.459999  43.639999  5463600.0
2              3           AAL    2015-12-31  ...  46.959999  48.000000  3709300.0
3             13          ABBV    2013-12-31  ...  66.019997  67.160004  5568800.0
4             14          ABBV    2014-12-31  ...  59.310001  60.119999  5220300.0
...          ...           ...           ...  ...        ...        ...        ...
1051        1775          ZION    2014-12-31  ...  27.420000  27.770000  1010700.0
1052        1776          ZION    2015-12-31  ...  42.630001  43.639999  1551600.0
1053        1777           ZTS    2013-12-31  ...  43.090000  44.099998  2251100.0
1054        1778           ZTS    2014-12-31  ...  48.009998  48.650002  1453700.0
1055        1779           ZTS    2015-12-31  ...  53.400002  53.779999  1046700.0

[1056 rows x 95 columns]

In [ ]:
joined_lag["priceChange"] = joined_lag["close_y"]/joined_lag["close_x"]
joined_lag["priceChange"].describe()

count    1056.000000
mean        1.090414
std         0.259384
min         0.224033
25%         0.943898
50%         1.082684
75%         1.225684
max         2.504597
Name: priceChange, dtype: float64

In [ ]:
spPerformance = {"Year":[2012, 2013, 2014,2015,2016], "Market Performance": [1.2960, 1.1139, 0.9927, 1.0954, 1.1942]}
marketPerf = pd.DataFrame(data=spPerformance)
marketPerf

   Year  Market Performance
0  2012              1.2960
1  2013              1.1139
2  2014              0.9927
3  2015              1.0954
4  2016              1.1942

In [ ]:
total_data = pd.merge(joined_lag, marketPerf, left_on=["For Year"], right_on=["Year"])
total_data["perc_performance"] = total_data["priceChange"]-total_data["Market Performance"]

In [ ]:
total_data["perc_performance"].describe()

count    1024.000000
mean        0.023860
std         0.247930
min        -0.768667
25%        -0.117178
50%         0.014894
75%         0.152590
max         1.409197
Name: perc_performance, dtype: float64

## Response Variable Encoding: 
**Good (Outperformance):** [.06, inf)

**Neutral (Neither outperformed nor underperformed significantly):** [-0.06, 0.06)

**Bad (Underperformance):** [-inf, -0.06)

In [ ]:
total_data["performance"] = pd.cut(total_data["perc_performance"], bins=[-1000,-0.059,0.06,1000], labels=("Underperformed", "Neutral", "Outperformed"))
total_data["performance"].value_counts()

Outperformed      418
Underperformed    365
Neutral           241
Name: performance, dtype: int64

In [ ]:
list(total_data.columns)

['Unnamed: 0',
 'Ticker Symbol',
 'Period Ending',
 'Accounts Payable',
 'Accounts Receivable',
 "Add'l income/expense items",
 'After Tax ROE',
 'Capital Expenditures',
 'Capital Surplus',
 'Cash Ratio',
 'Cash and Cash Equivalents',
 'Changes in Inventories',
 'Common Stocks',
 'Cost of Revenue',
 'Current Ratio',
 'Deferred Asset Charges',
 'Deferred Liability Charges',
 'Depreciation',
 'Earnings Before Interest and Tax',
 'Earnings Before Tax',
 'Effect of Exchange Rate',
 'Equity Earnings/Loss Unconsolidated Subsidiary',
 'Fixed Assets',
 'Goodwill',
 'Gross Margin',
 'Gross Profit',
 'Income Tax',
 'Intangible Assets',
 'Interest Expense',
 'Inventory',
 'Investments',
 'Liabilities',
 'Long-Term Debt',
 'Long-Term Investments',
 'Minority Interest',
 'Misc. Stocks',
 'Net Borrowings',
 'Net Cash Flow',
 'Net Cash Flow-Operating',
 'Net Cash Flows-Financing',
 'Net Cash Flows-Investing',
 'Net Income',
 'Net Income Adjustments',
 'Net Income Applicable to Common Shareholders',
 'Net Income-Cont. Operations',
 'Net Receivables',
 'Non-Recurring Items',
 'Operating Income',
 'Operating Margin',
 'Other Assets',
 'Other Current Assets',
 'Other Current Liabilities',
 'Other Equity',
 'Other Financing Activities',
 'Other Investing Activities',
 'Other Liabilities',
 'Other Operating Activities',
 'Other Operating Items',
 'Pre-Tax Margin',
 'Pre-Tax ROE',
 'Profit Margin',
 'Quick Ratio',
 'Research and Development',
 'Retained Earnings',
 'Sale and Purchase of Stock',
 'Sales, General and Admin.',
 'Short-Term Debt / Current Portion of Long-Term Debt',
 'Short-Term Investments',
 'Total Assets',
 'Total Current Assets',
 'Total Current Liabilities',
 'Total Equity',
 'Total Liabilities',
 'Total Liabilities & Equity',
 'Total Revenue',
 'Treasury Stock',
 'For Year',
 'Earnings Per Share',
 'Estimated Shares Outstanding',
 'PeriodAdjusted',
 'PeriodLagged',
 'date_x',
 'symbol_x',
 'open_x',
 'close_x',
 'low_x',
 'high_x',
 'volume_x',
 'date_y',
 'symbol_y',
 'open_y',
 'close_y',
 'low_y',
 'high_y',
 'volume_y',
 'priceChange',
 'Year',
 'Market Performance',
 'perc_performance',
 'performance']

In [ ]:
vars = ["Unnamed: 0", "For Year", "Period Ending", "Period Adjusted", "PeriodLagged", "date_x", "symbol_x", "open_x", ]

After Tax ROE
Cash Ratio
Current Ratio
Gross Margin
Operating Margin
Pre-Tax Margin
Pre-Tax ROE
Profit Margin
Quick Ratio

In [ ]:
total_data["Receivables Turnover"] = total_data["Total Revenue"]/total_data["Accounts Receivable"]
total_data["Inventory Turnover"] = total_data["Cost of Revenue"]/total_data["Inventory"]
total_data["Debt Ratio"] = total_data["Total Liabilities"]/total_data["Total Assets"]
total_data["Return on Assets"] = total_data["Net Income"]/total_data["Total Assets"]

In [ ]:
securities = pd.read_csv("drive/MyDrive/Colab Notebooks/securities.csv")
total_data = pd.merge(total_data, securities, left_on="Ticker Symbol", right_on="Ticker symbol", how="left")

In [ ]:
vars = ["After Tax ROE", "Cash Ratio", "Current Ratio", "Gross Margin", "Operating Margin", "Pre-Tax Margin", "Pre-Tax ROE", "Profit Margin", "Quick Ratio", "Receivables Turnover", "Inventory Turnover", "Debt Ratio", "Return on Assets", "GICS Sector", "performance"]

In [ ]:
final_data = total_data[vars]
final_data_v1 = final_data[~final_data.isin([np.nan, np.inf, -np.inf]).any(1)] #dropped nas and infinity values

In [ ]:
final_data_v1

      After Tax ROE  Cash Ratio  ...             GICS Sector     performance
0              67.0        75.0  ...             Industrials    Outperformed
1              92.0       144.0  ...             Health Care    Outperformed
2              10.0        85.0  ...             Health Care    Outperformed
3               7.0        48.0  ...        Consumer Staples    Outperformed
6               5.0         1.0  ...               Utilities    Outperformed
...             ...         ...  ...                     ...             ...
1014           16.0        83.0  ...             Industrials    Outperformed
1016            1.0       100.0  ...             Health Care  Underperformed
1018           32.0        65.0  ...             Health Care         Neutral
1021           10.0         3.0  ...               Utilities    Outperformed
1023           16.0        86.0  ...  Consumer Discretionary         Neutral

[606 rows x 15 columns]

In [ ]:
final_data_v1.to_csv("cleaned_data.csv")

# Model 1: LDA

##Train and Test Data Creation

In [ ]:
final_data_v1_x = final_data_v1.drop("performance", axis=1).drop("GICS Sector",axis=1)
final_data_v1_x

      After Tax ROE  Cash Ratio  ...  Debt Ratio  Return on Assets
0              67.0        75.0  ...    1.064596         -0.043380
1              92.0       144.0  ...    0.846154          0.141380
2              10.0        85.0  ...    0.413987          0.059973
3               7.0        48.0  ...    0.538444          0.030673
6               5.0         1.0  ...    0.689003          0.014020
...             ...         ...  ...         ...               ...
1014           16.0        83.0  ...    0.552502          0.073008
1016            1.0       100.0  ...    0.636735          0.005401
1018           32.0        65.0  ...    0.865032          0.042841
1021           10.0         3.0  ...    0.786949          0.021760
1023           16.0        86.0  ...    0.438822          0.089866

[606 rows x 13 columns]

In [ ]:
final_data_v1_y = final_data_v1["performance"]
final_data_v1_y

0         Outperformed
1         Outperformed
2         Outperformed
3         Outperformed
6         Outperformed
             ...
1014      Outperformed
1016    Underperformed
1018           Neutral
1021      Outperformed
1023           Neutral
Name: performance, Length: 606, dtype: category
Categories (3, object): ['Underperformed' < 'Neutral' < 'Outperformed']

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(final_data_v1_x, final_data_v1_y, random_state=50)

## LDA Class Code

In [ ]:
train_data = pd.concat([x_train,y_train], axis=1)

In [ ]:
###########################
# LDA Code

def multivariate_gaussian_pdf(X, MU, SIGMA):
    """Code from Data Blog https://xavierbourretsicotte.github.io/MLE_Multivariate_Gaussian.html
    Maximum Likelihood Estimator: Multivariate Gaussian Distribution
        by Xavier Bourret Sicotte, Fri 22 June 2018
    Returns the pdf of a multivariate Gaussian distribution
     - X, MU are p x 1 vectors
     - SIGMA is a p x p matrix"""
    # Initialize and reshape
    X = X.reshape(-1, 1)
    MU = MU.reshape(-1, 1)
    p, _ = SIGMA.shape

    # Compute values
    SIGMA_inv = np.linalg.inv(SIGMA)
    denominator = np.sqrt((2 * np.pi) ** p * np.linalg.det(SIGMA))
    exponent = -(1 / 2) * ((X - MU).T @ SIGMA_inv @ (X - MU))

    # Return result
    return float((1. / denominator) * np.exp(exponent))


class LDA:
    """Creates a class for Linear Discriminant Analysis
    Input:
        data = dataframe, must have one column labeled "class" and the rest numeric data
    Methods:
        compute_probabilities = given an input observation computes the likelihood for each class and the GML class
        compute_probabilities: given an input observation and prior probabilities,
            computes the posterior probabilities for each class and most probable class"""

    def __init__(self, data):
        # reads the data and computes the statistics needed for classification

        # read the bank data as a Pandas data frame
      #  df = pd.read_csv(fname, sep = ";")
        df = data
        # restrict the predictors to age, duration, 
        #variables = ['age', 'balance', 'duration', 'y']
        #df = df[variables]

        # separate the class labels from the rest of the data
        # we are assuming the column name with class labels is 'Class'
        # and all other columns are numeric
        self.data_labels = df.loc[:]['performance']
        self.data = np.asarray(df.drop('performance', axis=1, inplace=False))


        # get information about the dimensions the data
        self.num_rows, self.num_cols = self.data.shape

        # get the class names as an array of strings
        self.class_names = np.unique(self.data_labels)

        # determine number of observations in each class
        self.num_obs = dict()
        for name in self.class_names:
            self.num_obs[name] = sum(self.data_labels == name)

        # compute the mean of each class
        self.means = dict()
        for name in self.class_names:
            self.means[name] = np.mean(self.data[self.data_labels == name, :], 0)

        # compute the mean covariance matrix
        self.cov = np.zeros([self.num_cols, self.num_cols])
        for name in self.class_names:
            self.cov = self.cov + self.num_obs[name] * np.cov(np.transpose(self.data[self.data_labels == name, :]))
        self.cov = self.cov / self.num_rows

    def compute_likelihoods(self, x):
        # compute and output the likelihood of each class and the maximum likelihood class

        # check that the input data x has the correct number of rows
        if not (len(x) == self.num_cols):
            print('Data vector has wrong number of values.')
            return -1

        # reformat x as a numpy array, incase the user input a list
        x = np.asarray(x)

        # compute the likelihood of each class
        likelihoods = np.zeros(len(self.class_names))
        idx = 0
        for name in self.class_names:
            likelihoods[idx] = multivariate_gaussian_pdf(x, self.means[name], self.cov)
            idx = idx + 1

        # get the indices for sorting the likelihoods (in descending order)
        indices_sorted = np.argsort(likelihoods)[::-1]

        # print the predicted class and all class likelihoods
        print('LDA Predicted Class: ' + self.class_names[indices_sorted[0]])
        print('LDA Class Likelihoods:')
        for idx in range(len(indices_sorted)):
            print(self.class_names[indices_sorted[idx]] + ': ' + str(likelihoods[indices_sorted[idx]]))

        # return the likelihoods
        return likelihoods

    def compute_probabilities(self, x, priors):
        # compute and output the probability of each class and the maximum probability class
        
        #likelihoods = self.compute_likelihoods(x)
        # check that the input data x has the correct number of rows
        if not (len(x) == self.num_cols):
            print('Data vector has wrong number of values.')
            return -1

        # reformat x as a numpy array, incase the user input a list
        x = np.asarray(x)

        # compute the likelihood of each class
        likelihoods = np.zeros(len(self.class_names))
        idx = 0
        for name in self.class_names:
            likelihoods[idx] = multivariate_gaussian_pdf(x, self.means[name], self.cov)
            idx = idx + 1
        
        #Number of classes
        Nclass = len(self.class_names)
        
        
        #posterior probabilties: likelihood * prior / normalize
        postprob = np.zeros(Nclass)
        idx = 0
        normalize = 0
        for name in self.class_names:
            proportion = likelihoods[idx] * priors[name]
            postprob[idx] = proportion
            normalize += proportion
            idx = idx + 1
        postprob = np.round(postprob / normalize, 4)
        # get the indices for sorting the posterior probabilities (in descending order)
        indices_sorted = np.argsort(postprob)[::-1]
        
        
        print('LDA Predicted Class: ' + self.class_names[indices_sorted[0]])
        print('LDA Posterior Probabilities:')
        for idx in range(len(indices_sorted)):
            print(self.class_names[indices_sorted[idx]] + ': ' + str(postprob[indices_sorted[idx]]))

        # return the posterior probabilities
        return postprob

    def optimal_classifier(self, x, priors, costs):
        # compute and output the probability of each class and the maximum probability class
        
        #likelihoods = self.compute_likelihoods(x)
        # check that the input data x has the correct number of rows
        if not (len(x) == self.num_cols):
            print('Data vector has wrong number of values.')
            return -1

        # reformat x as a numpy array, incase the user input a list
        x = np.asarray(x)
        #Number of classes
        Nclass = len(self.class_names)
        class_idx = list(range(Nclass))
        

        #Decision function, expected cost comparison
        likelihoods = np.zeros(Nclass)
        expect_cost = np.zeros(Nclass)
        idx = 0
        for name in self.class_names:
            class_idx = list(range(Nclass))
            likelihoods[idx] = multivariate_gaussian_pdf(x, self.means[name], self.cov)
            del class_idx[idx]
            other_idx = class_idx
            expect_cost[idx] = likelihoods[idx]*priors[name]/costs[name]
            idx += 1 
        i = np.argmax(expect_cost, axis=0)
        return self.class_names[i]

In [ ]:
model = LDA(train_data)

##LDA Test Run

In [ ]:
uninformative = {
    'Outperformed': 0.333,
    'Neutral':0.333,
    'Underperformed':0.333
}
costs_vals = {
    'Outperformed': 1,
    'Underperformed': 1.0,
    'Neutral':0.9
}

In [ ]:
exp_results = []
for index, row in x_test.iterrows():
  exp_results.append(model.optimal_classifier(row, priors=uninformative, costs=costs_vals))

In [ ]:
def fun_over(variable): 
    if (variable == "Outperformed"): 
        return True
    else: 
        return False

def fun_under(variable): 
    if (variable == "Underperformed"): 
        return True
    else: 
        return False

def fun_neutral(variable): 
    if (variable == "Neutral"): 
        return True
    else: 
        return False

exp_results
# using filter function 
filtered_out = filter(fun_over, exp_results) 
filtered_under = filter(fun_under, exp_results) 
filtered_neutral = filter(fun_neutral, exp_results) 
length_over = len(list(filtered_out))
length_under = len(list(filtered_under))
length_neutral = len(list(filtered_neutral))

correct_over = 0
correct_under = 0
correct_neutral=0

In [ ]:
for val in range(0,len(exp_results)):
  if exp_results[val]==y_test.iloc[val] and exp_results[val]=="Outperformed":
    correct_over=correct_over+1
  elif exp_results[val]==y_test.iloc[val] and exp_results[val]=="Underperformed":
    correct_under=correct_under+1
  elif exp_results[val]==y_test.iloc[val] and exp_results[val]=="Neutral":
    correct_neutral=correct_neutral+1

print(correct_over/length_over,correct_under/length_under,correct_neutral/length_neutral)

0.39285714285714285 0.2926829268292683 0.24096385542168675

#Model 2: QDA

##Train and Test Data Creation

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(final_data_v1_x, final_data_v1_y, random_state=50)

In [ ]:
train_data = pd.concat([x_train,y_train], axis=1)

##QDA Class Code

In [ ]:
def multivariate_gaussian_pdf(X, MU, SIGMA):
    """Code from Data Blog https://xavierbourretsicotte.github.io/MLE_Multivariate_Gaussian.html
    Maximum Likelihood Estimator: Multivariate Gaussian Distribution
        by Xavier Bourret Sicotte, Fri 22 June 2018
    Returns the pdf of a multivariate Gaussian distribution
     - X, MU are p x 1 vectors
     - SIGMA is a p x p matrix"""
    # Initialize and reshape
    X = X.reshape(-1, 1)
    MU = MU.reshape(-1, 1)
    p, _ = SIGMA.shape

    # Compute values
    SIGMA_inv = np.linalg.inv(SIGMA)
    denominator = np.sqrt((2 * np.pi) ** p * np.linalg.det(SIGMA))
    exponent = -(1 / 2) * ((X - MU).T @ SIGMA_inv @ (X - MU))

    # Return result
    return float((1. / denominator) * np.exp(exponent))


class QDA:
    """Creates a class for Quadratic Discriminant Analysis
    Input:
        fname = file name for a csv file, must have one column labeled "class" and the rest numeric data
    Methods:
        compute_probabilities = given an input observation computes the likelihood for each class and the GML class
        compute_probabilities: given an input observation and prior probabilities,
            computes the posterior probabilities for each class and most probable class"""
            
    def __init__(self, data):
        # reads the data and computes the statistics needed for classification

        # read the bank data as a Pandas data frame
      #  df = pd.read_csv(fname, sep = ";")
        df = data
        # restrict the predictors to age, duration, 
        #variables = ['age', 'balance', 'duration', 'y']
        #df = df[variables]

        # separate the class labels from the rest of the data
        # we are assuming the column name with class labels is 'Class'
        # and all other columns are numeric
        self.data_labels = df.loc[:]['performance']
        self.data = np.asarray(df.drop('performance', axis=1, inplace=False))


        # get information about the dimensions the data
        self.num_rows, self.num_cols = self.data.shape

        # get the class names as an array of strings
        self.class_names = np.unique(self.data_labels)

        # determine number of observations in each class
        self.num_obs = dict()
        for name in self.class_names:
            self.num_obs[name] = sum(self.data_labels == name)

        # compute the mean of each class
        self.means = dict()
        for name in self.class_names:
            self.means[name] = np.mean(self.data[self.data_labels == name, :], 0)

        # compute the covariance matrix of each class
        self.covs = dict()
        for name in self.class_names:
            self.covs[name] = np.cov(np.transpose(self.data[self.data_labels == name, :]))

    def compute_likelihoods(self, x):
        # compute and output the likelihood of each class and the maximum likelihood class

        # check that the input data x has the correct number of rows
        if not (len(x) == self.num_cols):
            print('Data vector has wrong number of values.')
            return -1

        # reformat x as a numpy array, incase the user input a list
        x = np.asarray(x)

        # compute the likelihood of each class
        likelihoods = np.zeros(len(self.class_names))
        idx = 0
        for name in self.class_names:
            likelihoods[idx] = multivariate_gaussian_pdf(x, self.means[name], self.covs[name])
            idx += 1
        # get the indices for sorting the likelihoods (in descending order)
        indices_sorted = np.argsort(likelihoods)[::-1]


        # print the predicted class and all class likelihoods
        print('QDA Predicted Class: ' + self.class_names[indices_sorted[0]])
        print('QDA Class Likelihoods:')
        for idx in range(len(indices_sorted)):
            print(self.class_names[indices_sorted[idx]] + ': ' + str(likelihoods[indices_sorted[idx]]))

        # return the likelihoods
        return likelihoods

    def compute_probabilities(self, x, priors):
        # compute and output the probability of each class and the maximum probability class
        
        #likelihoods = self.compute_likelihoods(x)
        # check that the input data x has the correct number of rows
        if not (len(x) == self.num_cols):
            print('Data vector has wrong number of values.')
            return -1

        # reformat x as a numpy array, incase the user input a list
        x = np.asarray(x)

        # compute the likelihood of each class
        likelihoods = np.zeros(len(self.class_names))
        idx = 0
        for name in self.class_names:
            likelihoods[idx] = multivariate_gaussian_pdf(x, self.means[name], self.covs[name])
            idx = idx + 1
        
        #Number of classes
        Nclass = len(self.class_names)
        
        
        #posterior probabilties: likelihood * prior / normalize
        postprob = np.zeros(Nclass)
        idx = 0
        normalize = 0
        for name in self.class_names:
            proportion = likelihoods[idx] * priors[name]
            postprob[idx] = proportion
            normalize += proportion
            idx = idx + 1
        postprob = np.round(postprob / normalize,4)
        # get the indices for sorting the posterior probabilities (in descending order)
        indices_sorted = np.argsort(postprob)[::-1]
        
        
        print('QDA Predicted Class: ' + self.class_names[indices_sorted[0]])
        print('QDA Posterior Probabilities:')
        for idx in range(len(indices_sorted)):
            print(self.class_names[indices_sorted[idx]] + ': ' + str(postprob[indices_sorted[idx]]))

        # return the posterior probabilities
        return postprob

    def optimal_classifier(self, x, priors, costs):
        # compute and output the probability of each class and the maximum probability class
        
        #likelihoods = self.compute_likelihoods(x)
        # check that the input data x has the correct number of rows
        if not (len(x) == self.num_cols):
            print('Data vector has wrong number of values.')
            return -1

        # reformat x as a numpy array, incase the user input a list
        x = np.asarray(x)
        #Number of classes
        Nclass = len(self.class_names)
        class_idx = list(range(Nclass))
        

        #Decision function, expected cost comparison
        likelihoods = np.zeros(Nclass)
        expect_cost = np.zeros(Nclass)
        idx = 0
        for name in self.class_names:
            class_idx = list(range(Nclass))
            likelihoods[idx] = multivariate_gaussian_pdf(x, self.means[name], self.covs[name])
            del class_idx[idx]
            other_idx = class_idx
            expect_cost[idx] = likelihoods[idx]*priors[name]/costs[name]
            idx += 1 
        i = np.argmax(expect_cost, axis=0)
        return self.class_names[i]

In [ ]:
model = QDA(train_data)

##QDA Test Run

In [ ]:
uninformative = {
    'Outperformed': 0.333,
    'Neutral':0.333,
    'Underperformed':0.333
}
costs_vals = {
    'Outperformed': 1,
    'Underperformed': 1.0,
    'Neutral':0.9
}

In [ ]:
exp_results = []
for index, row in x_test.iterrows():
  exp_results.append(model.optimal_classifier(row, priors=uninformative, costs=costs_vals))

In [ ]:
def fun_over(variable): 
    if (variable == "Outperformed"): 
        return True
    else: 
        return False

def fun_under(variable): 
    if (variable == "Underperformed"): 
        return True
    else: 
        return False

def fun_neutral(variable): 
    if (variable == "Neutral"): 
        return True
    else: 
        return False

exp_results
# using filter function 
filtered_out = filter(fun_over, exp_results) 
filtered_under = filter(fun_under, exp_results) 
filtered_neutral = filter(fun_neutral, exp_results) 
length_over = len(list(filtered_out))
length_under = len(list(filtered_under))
length_neutral = len(list(filtered_neutral))

correct_over = 0
correct_under = 0
correct_neutral=0

In [ ]:
for val in range(0,len(exp_results)):
  if exp_results[val]==y_test.iloc[val] and exp_results[val]=="Outperformed":
    correct_over=correct_over+1
  elif exp_results[val]==y_test.iloc[val] and exp_results[val]=="Underperformed":
    correct_under=correct_under+1
  elif exp_results[val]==y_test.iloc[val] and exp_results[val]=="Neutral":
    correct_neutral=correct_neutral+1

print(correct_over/length_over,correct_under/length_under,correct_neutral/length_neutral)

0.38461538461538464 0.2692307692307692 0.23008849557522124